var testCards = [
    {
        sku: "1",
        year: "1909-11",
        title: "T206 White Border Honus Wagner",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "2",
        year: "1952",
        title: "Topps #311 Mickey Mantle",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "3",
        year: "1916",
        title: "(M101-5) Sporting News Babe Ruth Rookie Card",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "4",
        year: "1916",
        title: "(M101-4) Sporting News #151 Babe Ruth Rookie Card",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "5",
        year: "1909-11",
        title: "T206 Ty Cobb Tobacco (Ty Cobb Back)",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "6",
        year: "1914",
        title: "Baltimore News #9 Babe Ruth",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "7",
        year: "1909-11",
        title: "T206 White Border Eddie Plank",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "8",
        year: "1951",
        title: "Bowman #253 Mickey Mantle Rookie Card",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "9",
        year: "1909-11",
        title: "T206 White Border Sherry Magie Error Card",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "10",
        year: "1909-11",
        title: "American Caramel E90-1 Joe Jackson Rookie Card",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "11",
        year: "1910",
        title: "T210 Old Mill Joe Jackson",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "12",
        year: "1933",
        title: "Goudey #53 Babe Ruth",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "13",
        year: "1909-11",
        title: "T206 White Border Joe Doyle (N.Y. Natl.)",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "14",
        year: "1951",
        title: "Bowman #305 Willie Mays Rookie Card",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "15",
        year: "1948",
        title: "Leaf #8 Satchel Paige Rookie Card",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "16",
        year: "1915",
        title: "Cracker Jack Joe Jackson",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "17",
        year: "1915",
        title: "Cracker Jack Ty Cobb",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "18",
        year: "1933",
        title: "Goudey #144 Babe Ruth",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "19",
        year: "1933",
        title: "Goudey Sport Kings #2 Babe Ruth",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "20",
        year: "1948",
        title: "Leaf #79 Jackie Robinson Rookie Card",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "21",
        year: "1953",
        title: "Topps #82 Mickey Mantle",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "22",
        year: "1955",
        title: "Topps #164 Roberto Clemente Rookie Card",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "23",
        year: "1909-11",
        title: "T206 White Border Ty Cobb (Bat Off Shoulder)",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "24",
        year: "1902-1911",
        title: "W600 Sporting Life Cabinets Ty Cobb",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "25",
        year: "1932",
        title: "U.S. Caramel #32 Babe Ruth",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "26",
        year: "1933",
        title: "Goudey #160 Lou Gehrig",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "27",
        year: "1933",
        title: "Goudey #181 Babe Ruth",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "28",
        year: "1909-11",
        title: "T206 White Border Ty Cobb (Green Portrait)",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "29",
        year: "1914",
        title: "Cracker Jack Christy Mathewson",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "30",
        year: "1948",
        title: "Leaf #4 Stan Musial Rookie Card",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "31",
        year: "1952",
        title: "Topps #261 Willie Mays",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "32",
        year: "1909-11",
        title: "T206 White Border Cy Young (Portrait)",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "33",
        year: "1911",
        title: "T3 Turkey Red Cabinets Ty Cobb",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "34",
        year: "1914",
        title: "1914 Cracker Jack Joe Jackson",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "35",
        year: "1917",
        title: "Collins-McCarthy Babe Ruth",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "36",
        year: "1933",
        title: "Goudey #106 Napoleon Lajoie",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "37",
        year: "1933",
        title: "Goudey #149 Babe Ruth",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "38",
        year: "1938",
        title: "Goudey #274 Joe DiMaggio",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "39",
        year: "1902-1911",
        title: "W600 Sporting Life Cabinets Honus Wagner",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "40",
        year: "1909-11",
        title: "T206 White Border Christy Mathewson (Portrait)",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "41",
        year: "1933",
        title: "Goudey #92 Lou Gehrig",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "42",
        year: "1952",
        title: "Topps #407 Eddie Mathews Rookie Card",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "43",
        year: "1954",
        title: "Topps #128 Hank Aaron Rookie Card",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "44",
        year: "1914",
        title: "1914 Cracker Jack Ty Cobb",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "45",
        year: "1939",
        title: "Play Ball #92 Ted Williams Rookie Card",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "46",
        year: "1952",
        title: "Topps #1 Andy Pafko",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "47",
        year: "1954",
        title: "Wilson Franks #20 Ted Williams",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "48",
        year: "1961",
        title: "Topps Dice Game Mickey Mantle",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "49",
        year: "1909",
        title: "Ramly Cigarettes T204 Walter Johnson",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "50",
        year: "1934",
        title: "Goudey #37 Lou Gehrig",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "51",
        year: "1953",
        title: "Topps #244 Willie Mays",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "52",
        year: "1909-11",
        title: "T206 White Border Christy Mathewson (Dark Cap)",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "53",
        year: "1909-11",
        title: "T206 White Border Cy Young (Bare Hand)",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "54",
        year: "1911",
        title: "T205 Gold Border Ty Cobb",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "55",
        year: "1912",
        title: "Plow’s Candy E300 Ty Cobb",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "56",
        year: "1925",
        title: "Exhibits Lou Gehrig Rookie Card",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "57",
        year: "1911",
        title: "George Close Candy Co. E94 Ty Cobb",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "58",
        year: "1915",
        title: "American Caramel E106 Ty Cobb (With Bat, Facing Front)",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "59",
        year: "1909",
        title: "Nadja Caramel E92 Ty Cobb",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "60",
        year: "1938",
        title: "Goudey #250 Joe DiMaggio",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "61",
        year: "1954",
        title: "Bowman #65 Mickey Mantle",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "62",
        year: "1912",
        title: "Plow’s Candy E300 Christy Mathewson",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "63",
        year: "1909-11",
        title: "T206 White Border Walter Johnson Rookie Card (Portrait)",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "64",
        year: "1915",
        title: "American Caramel E106 Ty Cobb (With Bat, Facing To Side)",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "65",
        year: "1911",
        title: "Brunners Bread Ty Cobb",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "66",
        year: "1911",
        title: "George Close Candy Co. E94 Honus Wagner",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "67",
        year: "1911",
        title: "T205 Gold Border Christy Mathewson",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "68",
        year: "1915",
        title: "American Caramel E106 Honus Wagner (Batting)",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "69",
        year: "1915",
        title: "American Caramel E106 Honus Wagner (Throwing)",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "70",
        year: "1933",
        title: "Goudey #1 Benny Bengough",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "71",
        year: "1909-11",
        title: "T206 White Border Christy Mathewson (White Cap)",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "72",
        year: "1895",
        title: "Mayo's Cut Plug Cap Anson",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "73",
        year: "1955",
        title: "Topps #123 Sandy Koufax Rookie Card",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "74",
        year: "1909",
        title: "Nadja Caramel E92 Honus Wagner (Throwing)",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "75",
        year: "1934",
        title: "Goudey #61 Lou Gehrig",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "76",
        year: "1940",
        title: "Play Ball #1 Joe DiMaggio",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "77",
        year: "1948",
        title: "Leaf #4 Babe Ruth",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "78",
        year: "1953",
        title: "Stahl-Meyer Franks Mickey Mantle",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "79",
        year: "1909",
        title: "American Caramel Ty Cobb",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "80",
        year: "1909",
        title: "Nadja Caramel Honus Wagner (Batting)",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "81",
        year: "1915",
        title: "American Caramel E106 Christy Mathewson",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "82",
        year: "1909",
        title: "American Caramel Honus Wagner (Throwing)",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "83",
        year: "1910",
        title: "Mello Mint Ty Cobb",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "84",
        year: "1948",
        title: "Leaf #1 Joe DiMaggio",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "85",
        year: "1951",
        title: "Bowman #1 Whitey Ford Rookie Card",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "86",
        year: "1954",
        title: "Topps #94 Ernie Banks Rookie Card",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "87",
        year: "1887",
        title: "N172 Old Judge Cap Anson (Uniform)",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "88",
        year: "1909",
        title: "Philadelphia Caramel Christy Mathewson",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "89",
        year: "1888",
        title: "N162 Goodwin Champions Cap Anson",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "90",
        year: "1895",
        title: "Mayo's Cut Plug Ed Delahanty",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "91",
        year: "1909",
        title: "Nadja Caramel E92 Christy Mathewson",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "92",
        year: "1909",
        title: "American Caramel Honus Wagner (Batting)",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "93",
        year: "1910",
        title: "Mello Mint Christy Mathewson",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "94",
        year: "1910",
        title: "Mello Mint Honus Wagner (Throwing)",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "95",
        year: "1912",
        title: "T207 Brown Background Irving Lewis (No Emblem)",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "96",
        year: "1909",
        title: "Philadelphia Caramel E92 Honus Wagner",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "97",
        year: "1916",
        title: "(M101-4) Sporting News Joe Jackson",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "98",
        year: "1916",
        title: "(M101-5) Sporting News Joe Jackson",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "99",
        year: "1963",
        title: "Topps #537 Pete Rose Rookie Card",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
    {
        sku: "100",
        year: "1968",
        title: "Topps #177 Nolan Ryan Rookie Card",
        sport: "Baseball",
        price: 0,
        team: null,
        subset: null,
    },
];

export default testCards;
