var priceLevels = [500, 5000, 50000];
var getRandomPrice = () =>
    Math.floor(Math.random() * priceLevels[Math.floor(Math.random() * priceLevels.length)]);

var testCards = [
    {
        sku: "1",
        title: "T206 White Border Honus Wagner",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "2",
        title: "Topps 311 Mickey Mantle",
        year: "1952",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "3",
        title: "(M101-5) Sporting News Babe Ruth Rookie Card",
        year: "1916",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "4",
        title: "(M101-4) Sporting News 151 Babe Ruth Rookie Card",
        year: "1916",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "5",
        title: "T206 Ty Cobb Tobacco (Ty Cobb Back)",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "6",
        title: "Baltimore News 9 Babe Ruth",
        year: "1914",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "7",
        title: "T206 White Border Eddie Plank",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "8",
        title: "Bowman 253 Mickey Mantle Rookie Card",
        year: "1951",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "9",
        title: "T206 White Border Sherry Magie Error Card",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "10",
        title: "American Caramel E90-1 Joe Jackson Rookie Card",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "11",
        title: "T210 Old Mill Joe Jackson",
        year: "1910",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "12",
        title: "Goudey 53 Babe Ruth",
        year: "1933",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "13",
        title: "T206 White Border Joe Doyle (N.Y. Natl.)",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "14",
        title: "Bowman 305 Willie Mays Rookie Card",
        year: "1951",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "15",
        title: "Leaf 8 Satchel Paige Rookie Card",
        year: "1948",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "16",
        title: "Cracker Jack Joe Jackson",
        year: "1915",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "17",
        title: "Cracker Jack Ty Cobb",
        year: "1915",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "18",
        title: "Goudey 144 Babe Ruth",
        year: "1933",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "19",
        title: "Goudey Sport Kings 2 Babe Ruth",
        year: "1933",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "20",
        title: "Leaf 79 Jackie Robinson Rookie Card",
        year: "1948",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "21",
        title: "Topps 82 Mickey Mantle",
        year: "1953",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "22",
        title: "Topps 164 Roberto Clemente Rookie Card",
        year: "1955",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "23",
        title: "T206 White Border Ty Cobb (Bat Off Shoulder)",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "24",
        title: "W600 Sporting Life Cabinets Ty Cobb",
        year: "1902-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "25",
        title: "U.S. Caramel 32 Babe Ruth",
        year: "1932",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "26",
        title: "Goudey 160 Lou Gehrig",
        year: "1933",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "27",
        title: "Goudey 181 Babe Ruth",
        year: "1933",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "28",
        title: "T206 White Border Ty Cobb (Green Portrait)",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "29",
        title: "Cracker Jack Christy Mathewson",
        year: "1914",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "30",
        title: "Leaf 4 Stan Musial Rookie Card",
        year: "1948",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "31",
        title: "Topps 261 Willie Mays",
        year: "1952",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "32",
        title: "T206 White Border Cy Young (Portrait)",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "33",
        title: "T3 Turkey Red Cabinets Ty Cobb",
        year: "1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "34",
        title: "Cracker Jack Joe Jackson",
        year: "1914",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "35",
        title: "Collins-McCarthy Babe Ruth",
        year: "1917",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "36",
        title: "Goudey 106 Napoleon Lajoie",
        year: "1933",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "37",
        title: "Goudey 149 Babe Ruth",
        year: "1933",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "38",
        title: "Goudey 274 Joe DiMaggio",
        year: "1938",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "39",
        title: "W600 Sporting Life Cabinets Honus Wagner",
        year: "1902-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "40",
        title: "T206 White Border Christy Mathewson (Portrait)",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "41",
        title: "Goudey 92 Lou Gehrig",
        year: "1933",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "42",
        title: "Topps 407 Eddie Mathews Rookie Card",
        year: "1952",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "43",
        title: "Topps 128 Hank Aaron Rookie Card",
        year: "1954",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "44",
        title: "Cracker Jack Ty Cobb",
        year: "1914",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "45",
        title: "Play Ball 92 Ted Williams Rookie Card",
        year: "1939",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "46",
        title: "Topps 1 Andy Pafko",
        year: "1952",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "47",
        title: "Wilson Franks 20 Ted Williams",
        year: "1954",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "48",
        title: "Topps Dice Game Mickey Mantle",
        year: "1961",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "49",
        title: "Ramly Cigarettes T204 Walter Johnson",
        year: "1909",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "50",
        title: "Goudey 37 Lou Gehrig",
        year: "1934",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "51",
        title: "Topps 244 Willie Mays",
        year: "1953",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "52",
        title: "T206 White Border Christy Mathewson (Dark Cap)",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "53",
        title: "T206 White Border Cy Young (Bare Hand)",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "54",
        title: "T205 Gold Border Ty Cobb",
        year: "1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "55",
        title: "Plow’s Candy E300 Ty Cobb",
        year: "1912",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "56",
        title: "Exhibits Lou Gehrig Rookie Card",
        year: "1925",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "57",
        title: "George Close Candy Co. E94 Ty Cobb",
        year: "1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "58",
        title: "American Caramel E106 Ty Cobb (With Bat, Facing Front)",
        year: "1915",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "59",
        title: "Nadja Caramel E92 Ty Cobb",
        year: "1909",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "60",
        title: "Goudey 250 Joe DiMaggio",
        year: "1938",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "61",
        title: "Bowman 65 Mickey Mantle",
        year: "1954",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "62",
        title: "Plow’s Candy E300 Christy Mathewson",
        year: "1912",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "63",
        title: "T206 White Border Walter Johnson Rookie Card (Portrait)",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "64",
        title: "American Caramel E106 Ty Cobb (With Bat, Facing To Side)",
        year: "1915",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "65",
        title: "Brunners Bread Ty Cobb",
        year: "1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "66",
        title: "George Close Candy Co. E94 Honus Wagner",
        year: "1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "67",
        title: "T205 Gold Border Christy Mathewson",
        year: "1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "68",
        title: "American Caramel E106 Honus Wagner (Batting)",
        year: "1915",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "69",
        title: "American Caramel E106 Honus Wagner (Throwing)",
        year: "1915",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "70",
        title: "Goudey 1 Benny Bengough",
        year: "1933",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "71",
        title: "T206 White Border Christy Mathewson (White Cap)",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "72",
        title: "Mayo's Cut Plug Cap Anson",
        year: "1895",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "73",
        title: "Topps 123 Sandy Koufax Rookie Card",
        year: "1955",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "74",
        title: "Nadja Caramel E92 Honus Wagner (Throwing)",
        year: "1909",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "75",
        title: "Goudey 61 Lou Gehrig",
        year: "1934",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "76",
        title: "Play Ball 1 Joe DiMaggio",
        year: "1940",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "77",
        title: "Leaf 4 Babe Ruth",
        year: "1948",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "78",
        title: "Stahl-Meyer Franks Mickey Mantle",
        year: "1953",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "79",
        title: "American Caramel Ty Cobb",
        year: "1909",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "80",
        title: "Nadja Caramel Honus Wagner (Batting)",
        year: "1909",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "81",
        title: "American Caramel E106 Christy Mathewson",
        year: "1915",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "82",
        title: "American Caramel Honus Wagner (Throwing)",
        year: "1909",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "83",
        title: "Mello Mint Ty Cobb",
        year: "1910",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "84",
        title: "Leaf 1 Joe DiMaggio",
        year: "1948",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "85",
        title: "Bowman 1 Whitey Ford Rookie Card",
        year: "1951",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "86",
        title: "Topps 94 Ernie Banks Rookie Card",
        year: "1954",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "87",
        title: "N172 Old Judge Cap Anson (Uniform)",
        year: "1887",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "88",
        title: "Philadelphia Caramel Christy Mathewson",
        year: "1909",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "89",
        title: "N162 Goodwin Champions Cap Anson",
        year: "1888",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "90",
        title: "Mayo's Cut Plug Ed Delahanty",
        year: "1895",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "91",
        title: "Nadja Caramel E92 Christy Mathewson",
        year: "1909",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "92",
        title: "American Caramel Honus Wagner (Batting)",
        year: "1909",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "93",
        title: "Mello Mint Christy Mathewson",
        year: "1910",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "94",
        title: "Mello Mint Honus Wagner (Throwing)",
        year: "1910",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "95",
        title: "T207 Brown Background Irving Lewis (No Emblem)",
        year: "1912",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "96",
        title: "Philadelphia Caramel E92 Honus Wagner",
        year: "1909",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "97",
        title: "(M101-4) Sporting News Joe Jackson",
        year: "1916",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "98",
        title: "(M101-5) Sporting News Joe Jackson",
        year: "1916",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "99",
        title: "Topps 537 Pete Rose Rookie Card",
        year: "1963",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: "100",
        title: "Topps 177 Nolan Ryan Rookie Card",
        year: "1968",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
];

export default testCards;
