const _ = require("lodash");

var priceLevels = [500, 5000, 50000];
var getRandomPrice = () =>
    Math.floor(
        Math.random() *
            priceLevels[Math.floor(Math.random() * priceLevels.length)]
    );
var getRandomSku = () => _.times(10, () => _.random(35).toString(36)).join("");

var testCards = [
    {
        sku: getRandomSku(),
        title: "T206 White Border Honus Wagner",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Topps 311 Mickey Mantle",
        year: "1952",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "(M101-5) Sporting News Babe Ruth Rookie Card",
        year: "1916",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "(M101-4) Sporting News 151 Babe Ruth Rookie Card",
        year: "1916",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "T206 Ty Cobb Tobacco (Ty Cobb Back)",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Baltimore News 9 Babe Ruth",
        year: "1914",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "T206 White Border Eddie Plank",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Bowman 253 Mickey Mantle Rookie Card",
        year: "1951",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "T206 White Border Sherry Magie Error Card",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "American Caramel E90-1 Joe Jackson Rookie Card",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "T210 Old Mill Joe Jackson",
        year: "1910",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Goudey 53 Babe Ruth",
        year: "1933",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "T206 White Border Joe Doyle (N.Y. Natl.)",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Bowman 305 Willie Mays Rookie Card",
        year: "1951",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Leaf 8 Satchel Paige Rookie Card",
        year: "1948",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Cracker Jack Joe Jackson",
        year: "1915",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Cracker Jack Ty Cobb",
        year: "1915",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Goudey 144 Babe Ruth",
        year: "1933",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Goudey Sport Kings 2 Babe Ruth",
        year: "1933",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Leaf 79 Jackie Robinson Rookie Card",
        year: "1948",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Topps 82 Mickey Mantle",
        year: "1953",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Topps 164 Roberto Clemente Rookie Card",
        year: "1955",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "T206 White Border Ty Cobb (Bat Off Shoulder)",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "W600 Sporting Life Cabinets Ty Cobb",
        year: "1902-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "U.S. Caramel 32 Babe Ruth",
        year: "1932",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Goudey 160 Lou Gehrig",
        year: "1933",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Goudey 181 Babe Ruth",
        year: "1933",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "T206 White Border Ty Cobb (Green Portrait)",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Cracker Jack Christy Mathewson",
        year: "1914",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Leaf 4 Stan Musial Rookie Card",
        year: "1948",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Topps 261 Willie Mays",
        year: "1952",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "T206 White Border Cy Young (Portrait)",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "T3 Turkey Red Cabinets Ty Cobb",
        year: "1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Cracker Jack Joe Jackson",
        year: "1914",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Collins-McCarthy Babe Ruth",
        year: "1917",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Goudey 106 Napoleon Lajoie",
        year: "1933",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Goudey 149 Babe Ruth",
        year: "1933",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Goudey 274 Joe DiMaggio",
        year: "1938",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "W600 Sporting Life Cabinets Honus Wagner",
        year: "1902-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "T206 White Border Christy Mathewson (Portrait)",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Goudey 92 Lou Gehrig",
        year: "1933",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Topps 407 Eddie Mathews Rookie Card",
        year: "1952",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Topps 128 Hank Aaron Rookie Card",
        year: "1954",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Cracker Jack Ty Cobb",
        year: "1914",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Play Ball 92 Ted Williams Rookie Card",
        year: "1939",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Topps 1 Andy Pafko",
        year: "1952",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Wilson Franks 20 Ted Williams",
        year: "1954",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Topps Dice Game Mickey Mantle",
        year: "1961",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Ramly Cigarettes T204 Walter Johnson",
        year: "1909",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Goudey 37 Lou Gehrig",
        year: "1934",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Topps 244 Willie Mays",
        year: "1953",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "T206 White Border Christy Mathewson (Dark Cap)",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "T206 White Border Cy Young (Bare Hand)",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "T205 Gold Border Ty Cobb",
        year: "1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Plow’s Candy E300 Ty Cobb",
        year: "1912",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Exhibits Lou Gehrig Rookie Card",
        year: "1925",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "George Close Candy Co. E94 Ty Cobb",
        year: "1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "American Caramel E106 Ty Cobb (With Bat, Facing Front)",
        year: "1915",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Nadja Caramel E92 Ty Cobb",
        year: "1909",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Goudey 250 Joe DiMaggio",
        year: "1938",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Bowman 65 Mickey Mantle",
        year: "1954",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Plow’s Candy E300 Christy Mathewson",
        year: "1912",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "T206 White Border Walter Johnson Rookie Card (Portrait)",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "American Caramel E106 Ty Cobb (With Bat, Facing To Side)",
        year: "1915",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Brunners Bread Ty Cobb",
        year: "1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "George Close Candy Co. E94 Honus Wagner",
        year: "1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "T205 Gold Border Christy Mathewson",
        year: "1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "American Caramel E106 Honus Wagner (Batting)",
        year: "1915",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "American Caramel E106 Honus Wagner (Throwing)",
        year: "1915",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Goudey 1 Benny Bengough",
        year: "1933",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "T206 White Border Christy Mathewson (White Cap)",
        year: "1909-1911",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Mayo's Cut Plug Cap Anson",
        year: "1895",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Topps 123 Sandy Koufax Rookie Card",
        year: "1955",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Nadja Caramel E92 Honus Wagner (Throwing)",
        year: "1909",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Goudey 61 Lou Gehrig",
        year: "1934",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Play Ball 1 Joe DiMaggio",
        year: "1940",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Leaf 4 Babe Ruth",
        year: "1948",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Stahl-Meyer Franks Mickey Mantle",
        year: "1953",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "American Caramel Ty Cobb",
        year: "1909",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Nadja Caramel Honus Wagner (Batting)",
        year: "1909",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "American Caramel E106 Christy Mathewson",
        year: "1915",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "American Caramel Honus Wagner (Throwing)",
        year: "1909",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Mello Mint Ty Cobb",
        year: "1910",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Leaf 1 Joe DiMaggio",
        year: "1948",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Bowman 1 Whitey Ford Rookie Card",
        year: "1951",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Topps 94 Ernie Banks Rookie Card",
        year: "1954",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "N172 Old Judge Cap Anson (Uniform)",
        year: "1887",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Philadelphia Caramel Christy Mathewson",
        year: "1909",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "N162 Goodwin Champions Cap Anson",
        year: "1888",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Mayo's Cut Plug Ed Delahanty",
        year: "1895",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Nadja Caramel E92 Christy Mathewson",
        year: "1909",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "American Caramel Honus Wagner (Batting)",
        year: "1909",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Mello Mint Christy Mathewson",
        year: "1910",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Mello Mint Honus Wagner (Throwing)",
        year: "1910",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "T207 Brown Background Irving Lewis (No Emblem)",
        year: "1912",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Philadelphia Caramel E92 Honus Wagner",
        year: "1909",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "(M101-4) Sporting News Joe Jackson",
        year: "1916",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "(M101-5) Sporting News Joe Jackson",
        year: "1916",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Topps 537 Pete Rose Rookie Card",
        year: "1963",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Topps 177 Nolan Ryan Rookie Card",
        year: "1968",
        sport: "Baseball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },

    {
        sku: getRandomSku(),
        title: "Bowman 69 George Mikan",
        year: "1948",
        sport: "Basketball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Topps 77 Bill Russell",
        year: "1957",
        sport: "Basketball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Fleer 57 Michael Jordan",
        year: "1986",
        sport: "Basketball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Topps Larry Bird & Julius Erving & Magic Johnson",
        year: "1980",
        sport: "Basketball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
    {
        sku: getRandomSku(),
        title: "Topps 25 Lew Alcindor (Kareem Abdul-Jabbar) Rookie Card",
        year: "1969",
        sport: "Basketball",
        team: null,
        subset: null,
        price: getRandomPrice(),
    },
];

export default testCards;
